<#
IdentityAudit.Graph_V6.ps1
Cache-aware Microsoft Graph identity audit.
#>
[CmdletBinding()]
param(
  [string]${TenantId},[string]${ClientId},[string]${CertificateThumbprint},
  [string]${OutputRoot}='.\IdentityAudit-Evidence',[string]${CacheRoot}='.\IdentityAudit-Cache',[int]${CacheMaxAgeHours}=168,
  [string]${GroupIdsFile},[switch]${IncludeTransitiveMembership},[switch]${SecurityOnly},[switch]${MailEnabledSecurityOnly},[switch]${DistributionListOnly},[switch]${Microsoft365Only},[switch]${IsEmpty},
  [int]${MinGroupMembersCount}=0,[decimal]${HighDensityPctThreshold}=5.0,[switch]${SkipOwners},[switch]${InstallModules},[switch]${OpenDashboard},
  [switch]${UseCacheOnly},[switch]${RefreshAll},[switch]${RefreshUsers},[switch]${RefreshGroups},[switch]${RefreshMemberships},[switch]${RefreshOwners}
)
$ErrorActionPreference='Stop'
function Write-Stage([string]$Message){Write-Host "[IdentityAudit] $Message" -ForegroundColor Cyan}
function Write-Warn([string]$Message){Write-Host "[IdentityAudit][WARN] $Message" -ForegroundColor Yellow}
function Ensure-Module([string]$Name){if(-not(Get-Module -ListAvailable -Name $Name)){if($InstallModules){Install-Module $Name -Scope CurrentUser -Force -AllowClobber}else{throw "Missing module $Name. Use -InstallModules."}};Import-Module $Name -ErrorAction Stop}
function Get-Prop($Object,[string]$Name){if($null -eq $Object){return $null};$p=$Object.PSObject.Properties[$Name];if($null -ne $p){return $p.Value};try{return $Object[$Name]}catch{return $null}}
function Invoke-GraphGetJson([string]$Uri){try{$r=Invoke-MgGraphRequest -Method GET -Uri $Uri -OutputType HttpResponseMessage;$c=$r.Content.ReadAsStringAsync().GetAwaiter().GetResult();if([string]::IsNullOrWhiteSpace($c)){return $null};return Microsoft.PowerShell.Utility\ConvertFrom-Json -InputObject $c}catch{throw "Graph GET failed. Uri='$Uri'. Error='$($_.Exception.Message)'"}}
function Invoke-GraphPagedJson([string]$Uri){$rows=New-Object System.Collections.Generic.List[object];$next=$Uri;while(-not[string]::IsNullOrWhiteSpace([string]$next)){$pg=Invoke-GraphGetJson $next;$vals=Get-Prop $pg 'value';foreach($item in @($vals)){if($null -ne $item){[void]$rows.Add($item)}};$next=Get-Prop $pg '@odata.nextLink'};return $rows.ToArray()}
function Save-JsonCache([string]$Path,$Rows){$items=@($Rows);if($items.Count -eq 0){'[]'|Out-File $Path -Encoding utf8}else{$items|ConvertTo-Json -Depth 100|Out-File $Path -Encoding utf8}}
function Read-JsonCache([string]$Path){if(-not(Test-Path $Path)){return @()};$raw=Get-Content $Path -Raw;if([string]::IsNullOrWhiteSpace($raw)){return @()};return @($raw|Microsoft.PowerShell.Utility\ConvertFrom-Json)}
function Test-CacheFresh([string]$Path){if(-not(Test-Path $Path)){return $false};if($CacheMaxAgeHours -le 0){return $true};return (((Get-Date)-(Get-Item $Path).LastWriteTime).TotalHours -le $CacheMaxAgeHours)}
function Get-ObjectType($Object){$t=[string](Get-Prop $Object '@odata.type');if($t -match 'user$'){return 'User'};if($t -match 'group$'){return 'Group'};if($t -match 'servicePrincipal$'){return 'ServicePrincipal'};if($t -match 'device$'){return 'Device'};if($t -match 'orgContact$'){return 'Contact'};return 'DirectoryObject'}
function Get-Display($Object){$v=Get-Prop $Object 'displayName';if([string]::IsNullOrWhiteSpace([string]$v)){$v=Get-Prop $Object 'userPrincipalName'};if([string]::IsNullOrWhiteSpace([string]$v)){$v=Get-Prop $Object 'mail'};return $v}
function Get-GroupTypesText($Group){$gt=Get-Prop $Group 'groupTypes';if($null -eq $gt){return ''};return @($gt)-join ';'}
function Get-GroupCategory($Group){$gt=Get-GroupTypesText $Group;$s=Get-Prop $Group 'securityEnabled';$m=Get-Prop $Group 'mailEnabled';if($gt -match 'Unified'){return 'Microsoft365'};if($s -eq $true -and $m -eq $true){return 'MailEnabledSecurity'};if($s -eq $true){return 'Security'};if($m -eq $true){return 'DistributionList'};return 'Other'}
function Convert-Percent([decimal]$Numerator,[decimal]$Denominator){if($Denominator -le 0){return [decimal]0};return [math]::Round(($Numerator/$Denominator)*100,2)}
function HtmlSafe($Value){if($null -eq $Value){return ''};return [System.Net.WebUtility]::HtmlEncode([string]$Value)}
function Export-CsvSafe($Rows,[string]$Path){$items=@($Rows);if($items.Count -eq 0){New-Item -ItemType File -Path $Path -Force|Out-Null}else{$items|Export-Csv $Path -NoTypeInformation}}
function New-HtmlTable([string]$Title,$Rows,[string[]]$Columns){$items=@($Rows);$html="<section class='panel'><h2>$(HtmlSafe $Title)</h2>";if($items.Count -eq 0){return $html+'<p>No records found.</p></section>'};$html+='<table><thead><tr>';foreach($c in $Columns){$html+="<th>$(HtmlSafe $c)</th>"};$html+='</tr></thead><tbody>';foreach($r in @($items|Select-Object -First 25)){$html+='<tr>';foreach($c in $Columns){$v='';if($r.PSObject.Properties.Name -contains $c){$v=$r.$c};$html+="<td>$(HtmlSafe $v)</td>"};$html+='</tr>'};return $html+'</tbody></table></section>'}

New-Item -ItemType Directory -Path $CacheRoot -Force|Out-Null
$usersCache=Join-Path $CacheRoot 'users.json';$groupsCache=Join-Path $CacheRoot 'groups.json';$membersCache=Join-Path $CacheRoot 'members.direct.json';if($IncludeTransitiveMembership){$membersCache=Join-Path $CacheRoot 'members.transitive.json'};$ownersCache=Join-Path $CacheRoot 'owners.json'
$doUsers=[bool]$RefreshUsers;$doGroups=[bool]$RefreshGroups;$doMembers=[bool]$RefreshMemberships;$doOwners=[bool]$RefreshOwners
if($RefreshAll){$doUsers=$true;$doGroups=$true;$doMembers=$true;$doOwners=$true}
if(-not(Test-CacheFresh $usersCache)){$doUsers=$true}
if(-not(Test-CacheFresh $groupsCache)){$doGroups=$true}
if(-not(Test-CacheFresh $membersCache)){$doMembers=$true}
if(-not $SkipOwners -and -not(Test-CacheFresh $ownersCache)){$doOwners=$true}
if($doGroups){$doMembers=$true;if(-not $SkipOwners){$doOwners=$true}}
if($UseCacheOnly){foreach($p in @($usersCache,$groupsCache,$membersCache)){if(-not(Test-Path $p)){throw "Cache-only requested but missing cache file: $p"}};if(-not $SkipOwners -and -not(Test-Path $ownersCache)){throw "Cache-only requested but missing cache file: $ownersCache"};$doUsers=$false;$doGroups=$false;$doMembers=$false;$doOwners=$false}

$needsGraph=($doUsers -or $doGroups -or $doMembers -or $doOwners)
$connected=$false
try{
 if($needsGraph){Write-Stage 'Preparing modules';Ensure-Module 'Microsoft.Graph.Authentication';Write-Stage 'Connecting to Microsoft Graph';if($TenantId -and $ClientId -and $CertificateThumbprint){Connect-MgGraph -TenantId $TenantId -ClientId $ClientId -CertificateThumbprint $CertificateThumbprint -NoWelcome}else{Connect-MgGraph -Scopes @('User.Read.All','Group.Read.All','GroupMember.Read.All','Directory.Read.All') -NoWelcome};$connected=$true;if(-not $TenantId){$TenantId=(Get-MgContext).TenantId}}else{Write-Stage 'Using cache only; Graph connection skipped'}
 if($doUsers){Write-Stage 'Refreshing users cache';$u=Invoke-GraphPagedJson '/v1.0/users?$select=id,displayName,userPrincipalName,mail,department,jobTitle,companyName,accountEnabled,userType,employeeId,createdDateTime&$top=999';Save-JsonCache $usersCache $u}else{Write-Stage 'Using users cache'}
 if($doGroups){Write-Stage 'Refreshing groups cache';if($GroupIdsFile){$g=@();foreach($gid in (Get-Content $GroupIdsFile|Where-Object{$_})){$id=$gid.Trim();try{$g+=Invoke-GraphGetJson "/v1.0/groups/${id}?`$select=id,displayName,description,mail,mailEnabled,securityEnabled,groupTypes,membershipRule,membershipRuleProcessingState,isAssignableToRole,createdDateTime,visibility"}catch{$g+=Invoke-GraphGetJson "/v1.0/groups/${id}?`$select=id,displayName,description,mail,mailEnabled,securityEnabled,groupTypes,createdDateTime"}}}else{try{$g=Invoke-GraphPagedJson '/v1.0/groups?$select=id,displayName,description,mail,mailEnabled,securityEnabled,groupTypes,membershipRule,membershipRuleProcessingState,isAssignableToRole,createdDateTime,visibility&$top=999'}catch{Write-Warn "Advanced group properties failed; using baseline. $($_.Exception.Message)";$g=Invoke-GraphPagedJson '/v1.0/groups?$select=id,displayName,description,mail,mailEnabled,securityEnabled,groupTypes,createdDateTime&$top=999'}};Save-JsonCache $groupsCache $g}else{Write-Stage 'Using groups cache'}
 $rawUsers=Read-JsonCache $usersCache;$rawGroups=Read-JsonCache $groupsCache
 if($doMembers){Write-Stage 'Refreshing membership cache';$rows=@();$ep='members';if($IncludeTransitiveMembership){$ep='transitiveMembers'};$i=0;foreach($g in @($rawGroups)){$i++;$gid=Get-Prop $g 'id';$gn=Get-Prop $g 'displayName';Write-Progress -Activity 'Refreshing memberships' -Status $gn -PercentComplete (($i/[math]::Max(1,@($rawGroups).Count))*100);$cat=Get-GroupCategory $g;$gt=Get-GroupTypesText $g;$gm=Get-Prop $g 'mail';$se=Get-Prop $g 'securityEnabled';$me=Get-Prop $g 'mailEnabled';$ra=Get-Prop $g 'isAssignableToRole';$rule=Get-Prop $g 'membershipRule';$rs=Get-Prop $g 'membershipRuleProcessingState';try{$ms=Invoke-GraphPagedJson "/v1.0/groups/${gid}/${ep}?`$select=id,displayName,userPrincipalName,mail&`$top=999"}catch{Write-Warn "Members failed for $gn. $($_.Exception.Message)";$ms=@()};foreach($m in @($ms)){$rows+=[pscustomobject]@{GroupId=$gid;GroupName=$gn;GroupMail=$gm;GroupCategory=$cat;GroupSecurityEnabled=$se;GroupMailEnabled=$me;GroupTypes=$gt;GroupIsAssignableToRole=$ra;GroupMembershipRule=$rule;MembershipRuleState=$rs;MembershipMode=($(if($IncludeTransitiveMembership){'Transitive'}else{'Direct'}));MemberId=Get-Prop $m 'id';MemberDisplayName=Get-Display $m;MemberUPN=Get-Prop $m 'userPrincipalName';MemberMail=Get-Prop $m 'mail';MemberType=Get-ObjectType $m}}};Write-Progress -Activity 'Refreshing memberships' -Completed;Save-JsonCache $membersCache $rows}else{Write-Stage 'Using membership cache'}
 if(-not $SkipOwners){if($doOwners){Write-Stage 'Refreshing owners cache';$orows=@();$i=0;foreach($g in @($rawGroups)){$i++;$gid=Get-Prop $g 'id';$gn=Get-Prop $g 'displayName';$cat=Get-GroupCategory $g;Write-Progress -Activity 'Refreshing owners' -Status $gn -PercentComplete (($i/[math]::Max(1,@($rawGroups).Count))*100);try{$os=Invoke-GraphPagedJson "/v1.0/groups/${gid}/owners?`$select=id,displayName,userPrincipalName,mail&`$top=999"}catch{Write-Warn "Owners failed for $gn. $($_.Exception.Message)";$os=@()};foreach($o in @($os)){$orows+=[pscustomobject]@{GroupId=$gid;GroupName=$gn;GroupCategory=$cat;OwnerId=Get-Prop $o 'id';OwnerDisplayName=Get-Display $o;OwnerUPN=Get-Prop $o 'userPrincipalName';OwnerType=Get-ObjectType $o}}};Write-Progress -Activity 'Refreshing owners' -Completed;Save-JsonCache $ownersCache $orows}else{Write-Stage 'Using owners cache'}}
}
finally{if($connected){try{Disconnect-MgGraph|Out-Null}catch{}}}

Write-Stage 'Building report from cache'
$rawUsers=Read-JsonCache $usersCache;$rawGroups=Read-JsonCache $groupsCache;$memberCacheRows=Read-JsonCache $membersCache;$ownerRows=@();if(-not $SkipOwners){$ownerRows=Read-JsonCache $ownersCache}
$users=@();$usersById=@{};foreach($u in @($rawUsers)){$row=[pscustomobject]@{Id=Get-Prop $u 'id';DisplayName=Get-Prop $u 'displayName';UserPrincipalName=Get-Prop $u 'userPrincipalName';Mail=Get-Prop $u 'mail';Department=Get-Prop $u 'department';JobTitle=Get-Prop $u 'jobTitle';CompanyName=Get-Prop $u 'companyName';AccountEnabled=Get-Prop $u 'accountEnabled';UserType=Get-Prop $u 'userType';EmployeeId=Get-Prop $u 'employeeId';CreatedDateTime=Get-Prop $u 'createdDateTime'};$users+=$row;if($row.Id){$usersById[$row.Id]=$row}}
$groups=@();foreach($g in @($rawGroups)){$cat=Get-GroupCategory $g;if($SecurityOnly -and $cat -ne 'Security'){continue};if($MailEnabledSecurityOnly -and $cat -ne 'MailEnabledSecurity'){continue};if($DistributionListOnly -and $cat -ne 'DistributionList'){continue};if($Microsoft365Only -and $cat -ne 'Microsoft365'){continue};$groups+=$g}
$filteredIds=@{};foreach($g in @($groups)){$filteredIds[(Get-Prop $g 'id')]=$true}
$memberRows=@();foreach($m in @($memberCacheRows)){if(-not $filteredIds.ContainsKey($m.GroupId)){continue};$prof=$null;if($usersById.ContainsKey($m.MemberId)){$prof=$usersById[$m.MemberId]};$dep='';$jt='';$co='';$en=$null;$ut='';$emp='';$upn=$m.MemberUPN;$mail=$m.MemberMail;if($prof){$dep=$prof.Department;$jt=$prof.JobTitle;$co=$prof.CompanyName;$en=$prof.AccountEnabled;$ut=$prof.UserType;$emp=$prof.EmployeeId;if(-not $upn){$upn=$prof.UserPrincipalName};if(-not $mail){$mail=$prof.Mail}};$memberRows+=[pscustomobject]@{GroupId=$m.GroupId;GroupName=$m.GroupName;GroupMail=$m.GroupMail;GroupCategory=$m.GroupCategory;GroupSecurityEnabled=$m.GroupSecurityEnabled;GroupMailEnabled=$m.GroupMailEnabled;GroupTypes=$m.GroupTypes;GroupIsAssignableToRole=$m.GroupIsAssignableToRole;GroupMembershipRule=$m.GroupMembershipRule;MembershipRuleState=$m.MembershipRuleState;MembershipMode=$m.MembershipMode;MemberId=$m.MemberId;MemberDisplayName=$m.MemberDisplayName;MemberUPN=$upn;MemberMail=$mail;MemberType=$m.MemberType;MemberDepartment=$dep;MemberJobTitle=$jt;MemberCompanyName=$co;MemberAccountEnabled=$en;MemberUserType=$ut;MemberEmployeeId=$emp}}
$enabledUsers=@($users|Where-Object{$_.AccountEnabled -eq $true}).Count;$totalRows=@($memberRows).Count;$ownerCounts=@{};foreach($og in (@($ownerRows)|Group-Object GroupId)){$ownerCounts[$og.Name]=$og.Count}
$groupRows=@();foreach($g in @($groups)){$gid=Get-Prop $g 'id';$gn=Get-Prop $g 'displayName';$rows=@($memberRows|Where-Object{$_.GroupId -eq $gid});$um=@($rows|Where-Object{$_.MemberType -eq 'User'});$depts=@($um|Where-Object{$_.MemberDepartment}|Select-Object -ExpandProperty MemberDepartment -Unique);$deptGroups=@($um|Where-Object{$_.MemberDepartment}|Group-Object MemberDepartment|Sort-Object Count -Descending);$pd='';$pdc=0;if($deptGroups.Count -gt 0){$pd=$deptGroups[0].Name;$pdc=$deptGroups[0].Count};$mc=$rows.Count;$uuc=@($um|Select-Object -ExpandProperty MemberId -Unique).Count;$auc=@($um|Where-Object{$_.MemberAccountEnabled -eq $true}|Select-Object -ExpandProperty MemberId -Unique).Count;$den=Convert-Percent $mc $totalRows;$cov=Convert-Percent $auc $enabledUsers;$own=0;if($ownerCounts.ContainsKey($gid)){$own=$ownerCounts[$gid]};if($IsEmpty -and $mc -ne 0){continue};if($MinGroupMembersCount -gt 0 -and $mc -lt $MinGroupMembersCount){continue};$rule=Get-Prop $g 'membershipRule';$isDyn=-not[string]::IsNullOrWhiteSpace([string]$rule);$isCross=@($depts).Count -gt 1;$isHigh=$den -ge $HighDensityPctThreshold;$groupRows+=[pscustomobject]@{GroupId=$gid;GroupName=$gn;GroupMail=Get-Prop $g 'mail';GroupCategory=Get-GroupCategory $g;SecurityEnabled=Get-Prop $g 'securityEnabled';MailEnabled=Get-Prop $g 'mailEnabled';GroupTypes=Get-GroupTypesText $g;IsDynamicGroup=$isDyn;MembershipRule=$rule;MembershipRuleState=Get-Prop $g 'membershipRuleProcessingState';IsAssignableToRole=Get-Prop $g 'isAssignableToRole';OwnerCount=$own;MemberCount=$mc;UserMemberCount=$uuc;ActiveUserMemberCount=$auc;DepartmentCount=@($depts).Count;BlankDepartmentMemberCount=@($um|Where-Object{-not $_.MemberDepartment}).Count;PrimaryDepartment=$pd;PrimaryDepartmentCount=$pdc;PrimaryDepartmentPctOfGroup=Convert-Percent $pdc @($um).Count;MembershipDensityPct=$den;UserCoveragePct=$cov;IsCrossDepartmentGroup=$isCross;IsHighDensityGroup=$isHigh;CreatedDateTime=Get-Prop $g 'createdDateTime';Visibility=Get-Prop $g 'visibility'}}
$groupRows=@($groupRows|Sort-Object @{Expression='MembershipDensityPct';Descending=$true},@{Expression='GroupName';Ascending=$true});$allowed=@{};foreach($gr in $groupRows){$allowed[$gr.GroupId]=$true};$memberOut=@($memberRows|Where-Object{$allowed.ContainsKey($_.GroupId)})
$deptTotals=@{};foreach($dg in (@($users)|Group-Object Department)){$dn=$dg.Name;if(-not $dn){$dn='(blank)'};$deptTotals[$dn]=$dg.Count}
$deptRows=@();foreach($gd in (@($memberOut)|Where-Object{$_.MemberType -eq 'User'}|Group-Object GroupId,MemberDepartment)){$s=$gd.Group[0];$dn=$s.MemberDepartment;if(-not $dn){$dn='(blank)'};$uc=@($gd.Group|Select-Object -ExpandProperty MemberId -Unique).Count;$dt=0;if($deptTotals.ContainsKey($dn)){$dt=$deptTotals[$dn]};$gr=@($groupRows|Where-Object{$_.GroupId -eq $s.GroupId}|Select-Object -First 1);$gu=0;$gden=0;if($gr){$gu=$gr[0].UserMemberCount;$gden=$gr[0].MembershipDensityPct};$deptRows+=[pscustomobject]@{Department=$dn;GroupId=$s.GroupId;GroupName=$s.GroupName;GroupCategory=$s.GroupCategory;UsersInDepartmentInGroup=$uc;DepartmentTotalUsers=$dt;DepartmentCoveragePctForGroup=Convert-Percent $uc $dt;GroupShareFromDepartmentPct=Convert-Percent $uc $gu;GroupMembershipDensityPct=$gden;IsRoleAssignableGroup=$s.GroupIsAssignableToRole;IsDynamicGroup=(-not[string]::IsNullOrWhiteSpace([string]$s.GroupMembershipRule))}}
$deptRows=@($deptRows|Sort-Object @{Expression='GroupMembershipDensityPct';Descending=$true},@{Expression='GroupName';Ascending=$true})
$exceptions=@();foreach($gr in $groupRows){if(-not $SkipOwners -and $gr.OwnerCount -eq 0){$exceptions+=[pscustomobject]@{Severity='Medium';Finding='Group has no owner';GroupId=$gr.GroupId;GroupName=$gr.GroupName;Detail='OwnerCount=0'}};if($gr.IsHighDensityGroup){$exceptions+=[pscustomobject]@{Severity='Review';Finding='High group density';GroupId=$gr.GroupId;GroupName=$gr.GroupName;Detail="MembershipDensityPct=$($gr.MembershipDensityPct)"}};if($gr.IsCrossDepartmentGroup){$exceptions+=[pscustomobject]@{Severity='Review';Finding='Cross-department group';GroupId=$gr.GroupId;GroupName=$gr.GroupName;Detail="DepartmentCount=$($gr.DepartmentCount)"}};if($gr.IsAssignableToRole){$exceptions+=[pscustomobject]@{Severity='High';Finding='Role-assignable group';GroupId=$gr.GroupId;GroupName=$gr.GroupName;Detail='IsAssignableToRole=True'}}}
$run=Get-Date -Format 'yyyyMMdd-HHmmss';$out=Join-Path $OutputRoot $run;New-Item -ItemType Directory -Path $out -Force|Out-Null
Write-Stage 'Writing CSV evidence';Export-CsvSafe $users (Join-Path $out 'IdentityAudit-Users.csv');Export-CsvSafe $groupRows (Join-Path $out 'IdentityAudit-Groups.csv');Export-CsvSafe $memberOut (Join-Path $out 'IdentityAudit-GroupMembers.csv');Export-CsvSafe $ownerRows (Join-Path $out 'IdentityAudit-GroupOwners.csv');Export-CsvSafe $deptRows (Join-Path $out 'IdentityAudit-DepartmentGroupMatrix.csv');Export-CsvSafe ($groupRows|Select-Object GroupName,GroupId,GroupCategory,MemberCount,UserMemberCount,ActiveUserMemberCount,MembershipDensityPct,UserCoveragePct,DepartmentCount,PrimaryDepartment,PrimaryDepartmentPctOfGroup,OwnerCount,IsDynamicGroup,IsAssignableToRole,IsHighDensityGroup) (Join-Path $out 'IdentityAudit-GroupDensity.csv');Export-CsvSafe $exceptions (Join-Path $out 'IdentityAudit-Exceptions.csv')
Write-Stage 'Writing dashboard';$css="<style>body{font-family:Segoe UI,Arial;margin:32px;background:#f5f7fb;color:#172033}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.card,.panel{background:#fff;border:1px solid #d9e0ec;border-radius:12px;padding:14px;margin:14px 0}.value{font-size:26px;font-weight:700}table{border-collapse:collapse;width:100%;font-size:13px}td,th{border-bottom:1px solid #edf1f7;padding:7px;text-align:left}</style>";$topD=@($groupRows|Select-Object -First 25);$topC=@($groupRows|Sort-Object UserCoveragePct -Descending|Select-Object -First 25);$cross=@($groupRows|Where-Object{$_.IsCrossDepartmentGroup}|Select-Object -First 25);$ownerless=@($groupRows|Where-Object{$_.OwnerCount -eq 0}|Select-Object -First 25);$dyn=@($groupRows|Where-Object{$_.IsDynamicGroup}|Select-Object -First 25);$hot=@($deptRows|Select-Object -First 25)
$html="<!doctype html><html><head><meta charset='utf-8'><title>Identity Audit Dashboard</title>$css</head><body><h1>Identity Audit Dashboard</h1><p>Run $run | Tenant $(HtmlSafe $TenantId) | Cache root $(HtmlSafe $CacheRoot)</p><div class='cards'><div class='card'>Groups<div class='value'>$(@($groupRows).Count)</div></div><div class='card'>Users<div class='value'>$(@($users).Count)</div></div><div class='card'>Membership rows<div class='value'>$totalRows</div></div><div class='card'>Ownerless groups<div class='value'>$(@($ownerless).Count)</div></div></div>";$html+=New-HtmlTable 'Top group density by membership percentage' $topD @('GroupName','GroupCategory','MemberCount','UserMemberCount','MembershipDensityPct','UserCoveragePct','DepartmentCount','PrimaryDepartment','OwnerCount','IsDynamicGroup','IsAssignableToRole');$html+=New-HtmlTable 'Top groups by enabled user coverage percentage' $topC @('GroupName','GroupCategory','ActiveUserMemberCount','UserCoveragePct','MembershipDensityPct','DepartmentCount','PrimaryDepartment','OwnerCount');$html+=New-HtmlTable 'Department / group hotspots' $hot @('Department','GroupName','UsersInDepartmentInGroup','DepartmentTotalUsers','DepartmentCoveragePctForGroup','GroupShareFromDepartmentPct','GroupMembershipDensityPct');$html+=New-HtmlTable 'Cross-department groups' $cross @('GroupName','MemberCount','DepartmentCount','PrimaryDepartment','MembershipDensityPct','OwnerCount');$html+=New-HtmlTable 'Ownerless groups' $ownerless @('GroupName','GroupCategory','MemberCount','MembershipDensityPct','DepartmentCount','IsDynamicGroup','IsAssignableToRole');$html+=New-HtmlTable 'Dynamic groups' $dyn @('GroupName','GroupCategory','MemberCount','MembershipDensityPct','UserCoveragePct','DepartmentCount','PrimaryDepartment','MembershipRule');$html+='<p>Group density percentage = group membership rows divided by all membership rows observed in this run.</p></body></html>';$dash=Join-Path $out 'IdentityAudit-Dashboard.html';$html|Out-File $dash -Encoding utf8
@('# Identity Audit Evidence Manifest','',"Run ID: $run","Tenant ID: $TenantId","Cache root: $CacheRoot","Cache max age hours: $CacheMaxAgeHours",'','Outputs: users, groups, members, owners, department matrix, density, exceptions, dashboard')|Out-File (Join-Path $out 'IdentityAudit-Manifest.md') -Encoding utf8
Write-Stage 'Complete';Write-Host "Output folder: $out";Write-Host "Dashboard: $dash";if($OpenDashboard){Invoke-Item $dash}
