<#
IdentityAudit.Graph_V10.ps1
Self-contained Microsoft Graph identity audit with cache, CSV evidence, dashboard, and graph analytics.
#>
[CmdletBinding()]
param(
  [string]${TenantId},[string]${ClientId},[string]${CertificateThumbprint},
  [string]${OutputRoot}='.\IdentityAudit-Evidence',[string]${CacheRoot}='.\IdentityAudit-Cache',[int]${CacheMaxAgeHours}=168,
  [string]${GroupIdsFile},[switch]${IncludeTransitiveMembership},[switch]${SecurityOnly},[switch]${MailEnabledSecurityOnly},[switch]${DistributionListOnly},[switch]${Microsoft365Only},[switch]${IsEmpty},
  [int]${MinGroupMembersCount}=0,[decimal]${HighDensityPctThreshold}=5.0,[switch]${SkipOwners},[switch]${InstallModules},[switch]${OpenDashboard},
  [switch]${UseCacheOnly},[switch]${RefreshAll},[switch]${RefreshUsers},[switch]${RefreshGroups},[switch]${RefreshMemberships},[switch]${RefreshOwners},
  [int]${MaxPathDepth}=6,[string]${HighValueGroupPattern}='(?i)(admin|privileged|break.?glass|global administrator|role|security administrator|application administrator|owner)'
)
$ErrorActionPreference='Stop'
function Write-Stage([string]$Message){Write-Host "[IdentityAudit] $Message" -ForegroundColor Cyan}
function Write-Warn([string]$Message){Write-Host "[IdentityAudit][WARN] $Message" -ForegroundColor Yellow}
function Ensure-Module([string]$Name){if(-not(Get-Module -ListAvailable -Name $Name)){if($InstallModules){Install-Module $Name -Scope CurrentUser -Force -AllowClobber}else{throw "Missing module $Name. Use -InstallModules."}};Import-Module $Name -ErrorAction Stop}
function Get-Prop($Object,[string]$Name){if($null -eq $Object){return $null};$p=$Object.PSObject.Properties[$Name];if($null -ne $p){return $p.Value};try{return $Object[$Name]}catch{return $null}}
function Invoke-GraphGetJson([string]$Uri){try{$r=Invoke-MgGraphRequest -Method GET -Uri $Uri -OutputType HttpResponseMessage;$c=$r.Content.ReadAsStringAsync().GetAwaiter().GetResult();if([string]::IsNullOrWhiteSpace($c)){return $null};return Microsoft.PowerShell.Utility\ConvertFrom-Json -InputObject $c}catch{throw "Graph GET failed. Uri='$Uri'. Error='$($_.Exception.Message)'"}}
function Invoke-GraphPagedJson([string]$Uri){$rows=New-Object System.Collections.Generic.List[object];$next=$Uri;while(-not[string]::IsNullOrWhiteSpace([string]$next)){$pg=Invoke-GraphGetJson $next;$vals=Get-Prop $pg 'value';foreach($item in @($vals)){if($null -ne $item){[void]$rows.Add($item)}};$next=Get-Prop $pg '@odata.nextLink'};return $rows.ToArray()}
function Save-JsonCache([string]$Path,$Rows){$items=@($Rows);if($items.Count -eq 0){'[]'|Out-File $Path -Encoding utf8}else{$items|ConvertTo-Json -Depth 100|Out-File $Path -Encoding utf8}}
function Read-JsonCache([string]$Path){if(-not(Test-Path $Path)){return @()};$raw=Get-Content $Path -Raw;if([string]::IsNullOrWhiteSpace($raw)){return @()};return @($raw|Microsoft.PowerShell.Utility\ConvertFrom-Json)}
function Test-CacheFresh([string]$Path){if(-not(Test-Path $Path)){return $false};if($CacheMaxAgeHours -le 0){return $true};return (((Get-Date)-(Get-Item $Path).LastWriteTime).TotalHours -le $CacheMaxAgeHours)}
function Get-ObjectType($Object){$t=[string](Get-Prop $Object '@odata.type');if($t -match 'user$'){return 'User'};if($t -match 'group$'){return 'Group'};if($t -match 'servicePrincipal$'){return 'ServicePrincipal'};if($t -match 'device$'){return 'Device'};if($t -match 'orgContact$'){return 'Contact'};return 'DirectoryObject'}
function Get-Display($Object){$v=Get-Prop $Object 'displayName';if([string]::IsNullOrWhiteSpace([string]$v)){$v=Get-Prop $Object 'userPrincipalName'};if([string]::IsNullOrWhiteSpace([string]$v)){$v=Get-Prop $Object 'mail'};return $v}
function Get-GroupTypesText($Group){$gt=Get-Prop $Group 'groupTypes';if($null -eq $gt){return ''};return @($gt)-join ';'}
function Get-GroupCategory($Group){$gt=Get-GroupTypesText $Group;$s=Get-Prop $Group 'securityEnabled';$m=Get-Prop $Group 'mailEnabled';if($gt -match 'Unified'){return 'Microsoft365'};if($s -eq $true -and $m -eq $true){return 'MailEnabledSecurity'};if($s -eq $true){return 'Security'};if($m -eq $true){return 'DistributionList'};return 'Other'}
function Convert-Percent([decimal]$Numerator,[decimal]$Denominator){if($Denominator -le 0){return [decimal]0};return [math]::Round(($Numerator/$Denominator)*100,2)}
function HtmlSafe($Value){if($null -eq $Value){return ''};return [System.Net.WebUtility]::HtmlEncode([string]$Value)}
function Export-CsvSafe($Rows,[string]$Path){$items=@($Rows);if($items.Count -eq 0){New-Item -ItemType File -Path $Path -Force|Out-Null}else{$items|Export-Csv $Path -NoTypeInformation}}
function New-HtmlTable([string]$Title,$Rows,[string[]]$Columns,[int]$MaxRows=25){$items=@($Rows);$html="<section class='panel'><h2>$(HtmlSafe $Title)</h2>";if($items.Count -eq 0){return $html+'<p class="muted">No records found.</p></section>'};$html+='<table><thead><tr>';foreach($c in $Columns){$html+="<th>$(HtmlSafe $c)</th>"};$html+='</tr></thead><tbody>';foreach($r in @($items|Select-Object -First $MaxRows)){$html+='<tr>';foreach($c in $Columns){$v='';if($r.PSObject.Properties.Name -contains $c){$v=$r.$c};$html+="<td>$(HtmlSafe $v)</td>"};$html+='</tr>'};return $html+'</tbody></table></section>'}
function Add-Node($Map,[string]$Id,[string]$Label,[string]$Type,[string]$SubType=''){if([string]::IsNullOrWhiteSpace($Id)){return};if(-not $Map.ContainsKey($Id)){$Map[$Id]=[pscustomobject]@{Id=$Id;Label=$Label;Type=$Type;SubType=$SubType;RiskScore=0;RiskDrivers=''}}}
function New-Edge($SourceId,$TargetId,$EdgeType,$SourceLabel,$TargetLabel,$SourceType,$TargetType){[pscustomobject]@{SourceId=$SourceId;SourceLabel=$SourceLabel;SourceType=$SourceType;TargetId=$TargetId;TargetLabel=$TargetLabel;TargetType=$TargetType;EdgeType=$EdgeType}}
function Find-ShortestPath($Adj,[string]$Start,$Targets,[int]$DepthLimit){$queue=New-Object System.Collections.Queue;$seen=@{};$queue.Enqueue(@($Start,@($Start)));$seen[$Start]=$true;while($queue.Count -gt 0){$item=$queue.Dequeue();$node=$item[0];$path=@($item[1]);if($Targets.ContainsKey($node) -and $node -ne $Start){return $path};if($path.Count -gt ($DepthLimit+1)){continue};foreach($next in @($Adj[$node])){if(-not $seen.ContainsKey($next)){$seen[$next]=$true;$newPath=@($path+$next);$queue.Enqueue(@($next,$newPath))}}};return @()}
function Find-Cycles($Adj,[int]$DepthLimit){$found=@{};$cycles=@();foreach($start in $Adj.Keys){$stack=@(@($start,@($start)));while($stack.Count -gt 0){$cur=$stack[-1];if($stack.Count -eq 1){$stack=@()}else{$stack=$stack[0..($stack.Count-2)]};$node=$cur[0];$path=@($cur[1]);if($path.Count -gt ($DepthLimit+1)){continue};foreach($next in @($Adj[$node])){if($next -eq $start -and $path.Count -gt 1){$cycle=@($path+$start);$key=(@($cycle|Sort-Object)-join '|');if(-not $found.ContainsKey($key)){$found[$key]=$true;$cycles+=[pscustomobject]@{Length=($cycle.Count-1);Cycle=($cycle -join ' -> ')}}}elseif($path -notcontains $next){$stack+=,@($next,@($path+$next))}}}};return $cycles}

New-Item -ItemType Directory -Path $CacheRoot -Force|Out-Null
$usersCache=Join-Path $CacheRoot 'users.json';$groupsCache=Join-Path $CacheRoot 'groups.json';$membersCache=Join-Path $CacheRoot 'members.direct.json';$membershipMode='Direct';if($IncludeTransitiveMembership){$membersCache=Join-Path $CacheRoot 'members.transitive.json';$membershipMode='Transitive'};$ownersCache=Join-Path $CacheRoot 'owners.json'
$doUsers=[bool]$RefreshUsers;$doGroups=[bool]$RefreshGroups;$doMembers=[bool]$RefreshMemberships;$doOwners=[bool]$RefreshOwners
if($RefreshAll){$doUsers=$true;$doGroups=$true;$doMembers=$true;$doOwners=$true}
if(-not(Test-CacheFresh $usersCache)){$doUsers=$true}
if(-not(Test-CacheFresh $groupsCache)){$doGroups=$true}
if(-not(Test-CacheFresh $membersCache)){$doMembers=$true}
if(-not $SkipOwners -and -not(Test-CacheFresh $ownersCache)){$doOwners=$true}
if($doGroups){$doMembers=$true;if(-not $SkipOwners){$doOwners=$true}}
if($UseCacheOnly){foreach($p in @($usersCache,$groupsCache,$membersCache)){if(-not(Test-Path $p)){throw "Cache-only requested but missing cache file: $p"}};if(-not $SkipOwners -and -not(Test-Path $ownersCache)){throw "Cache-only requested but missing cache file: $ownersCache"};$doUsers=$false;$doGroups=$false;$doMembers=$false;$doOwners=$false}
$needsGraph=($doUsers -or $doGroups -or $doMembers -or $doOwners);$connected=$false
try{
 if($needsGraph){Write-Stage 'Preparing modules';Ensure-Module 'Microsoft.Graph.Authentication';Write-Stage 'Connecting to Microsoft Graph';if($TenantId -and $ClientId -and $CertificateThumbprint){Connect-MgGraph -TenantId $TenantId -ClientId $ClientId -CertificateThumbprint $CertificateThumbprint -NoWelcome}else{Connect-MgGraph -Scopes @('User.Read.All','Group.Read.All','GroupMember.Read.All','Directory.Read.All') -NoWelcome};$connected=$true;if(-not $TenantId){$TenantId=(Get-MgContext).TenantId}}else{Write-Stage 'Using cache only; Graph connection skipped'}
 if($doUsers){Write-Stage 'Refreshing users cache';$raw=Invoke-GraphPagedJson '/v1.0/users?$select=id,displayName,userPrincipalName,mail,department,jobTitle,companyName,accountEnabled,userType,employeeId,createdDateTime&$top=999';Save-JsonCache $usersCache $raw}else{Write-Stage 'Using users cache'}
 if($doGroups){Write-Stage 'Refreshing groups cache';if($GroupIdsFile){$rawGroups=@();foreach($gid in (Get-Content $GroupIdsFile|Where-Object{$_})){$id=$gid.Trim();try{$rawGroups+=Invoke-GraphGetJson "/v1.0/groups/${id}?`$select=id,displayName,description,mail,mailEnabled,securityEnabled,groupTypes,membershipRule,membershipRuleProcessingState,isAssignableToRole,createdDateTime,visibility"}catch{$rawGroups+=Invoke-GraphGetJson "/v1.0/groups/${id}?`$select=id,displayName,description,mail,mailEnabled,securityEnabled,groupTypes,createdDateTime"}}}else{try{$rawGroups=Invoke-GraphPagedJson '/v1.0/groups?$select=id,displayName,description,mail,mailEnabled,securityEnabled,groupTypes,membershipRule,membershipRuleProcessingState,isAssignableToRole,createdDateTime,visibility&$top=999'}catch{Write-Warn "Advanced group properties failed; using baseline. $($_.Exception.Message)";$rawGroups=Invoke-GraphPagedJson '/v1.0/groups?$select=id,displayName,description,mail,mailEnabled,securityEnabled,groupTypes,createdDateTime&$top=999'}};Save-JsonCache $groupsCache $rawGroups}else{Write-Stage 'Using groups cache'}
 $rawGroupsForMembership=Read-JsonCache $groupsCache
 if($doMembers){Write-Stage 'Refreshing membership cache';$memberCacheRows=@();$endpoint='members';if($IncludeTransitiveMembership){$endpoint='transitiveMembers'};$i=0;foreach($g in @($rawGroupsForMembership)){$i++;$gid=Get-Prop $g 'id';$gn=Get-Prop $g 'displayName';Write-Progress -Activity 'Refreshing memberships' -Status $gn -PercentComplete (($i/[math]::Max(1,@($rawGroupsForMembership).Count))*100);try{$ms=Invoke-GraphPagedJson "/v1.0/groups/${gid}/${endpoint}?`$select=id,displayName,userPrincipalName,mail&`$top=999"}catch{Write-Warn "Members failed for $gn. $($_.Exception.Message)";$ms=@()};foreach($m in @($ms)){$memberCacheRows+=[pscustomobject]@{GroupId=$gid;GroupName=$gn;GroupMail=Get-Prop $g 'mail';GroupCategory=Get-GroupCategory $g;GroupSecurityEnabled=Get-Prop $g 'securityEnabled';GroupMailEnabled=Get-Prop $g 'mailEnabled';GroupTypes=Get-GroupTypesText $g;GroupIsAssignableToRole=Get-Prop $g 'isAssignableToRole';GroupMembershipRule=Get-Prop $g 'membershipRule';MembershipRuleState=Get-Prop $g 'membershipRuleProcessingState';MembershipMode=$membershipMode;MemberId=Get-Prop $m 'id';MemberDisplayName=Get-Display $m;MemberUPN=Get-Prop $m 'userPrincipalName';MemberMail=Get-Prop $m 'mail';MemberType=Get-ObjectType $m}}};Write-Progress -Activity 'Refreshing memberships' -Completed;Save-JsonCache $membersCache $memberCacheRows}else{Write-Stage 'Using membership cache'}
 if(-not $SkipOwners){if($doOwners){Write-Stage 'Refreshing owners cache';$ownerCacheRows=@();$i=0;foreach($g in @($rawGroupsForMembership)){$i++;$gid=Get-Prop $g 'id';$gn=Get-Prop $g 'displayName';Write-Progress -Activity 'Refreshing owners' -Status $gn -PercentComplete (($i/[math]::Max(1,@($rawGroupsForMembership).Count))*100);try{$os=Invoke-GraphPagedJson "/v1.0/groups/${gid}/owners?`$select=id,displayName,userPrincipalName,mail&`$top=999"}catch{Write-Warn "Owners failed for $gn. $($_.Exception.Message)";$os=@()};foreach($o in @($os)){$ownerCacheRows+=[pscustomobject]@{GroupId=$gid;GroupName=$gn;GroupCategory=Get-GroupCategory $g;OwnerId=Get-Prop $o 'id';OwnerDisplayName=Get-Display $o;OwnerUPN=Get-Prop $o 'userPrincipalName';OwnerType=Get-ObjectType $o}}};Write-Progress -Activity 'Refreshing owners' -Completed;Save-JsonCache $ownersCache $ownerCacheRows}else{Write-Stage 'Using owners cache'}}
}finally{if($connected){try{Disconnect-MgGraph|Out-Null}catch{}}}

Write-Stage 'Building report from cache'
$rawUsers=Read-JsonCache $usersCache;$rawGroups=Read-JsonCache $groupsCache;$memberCacheRows=Read-JsonCache $membersCache;$ownerRows=@();if(-not $SkipOwners){$ownerRows=Read-JsonCache $ownersCache}
$users=@();$usersById=@{};foreach($u in @($rawUsers)){$row=[pscustomobject]@{Id=Get-Prop $u 'id';DisplayName=Get-Prop $u 'displayName';UserPrincipalName=Get-Prop $u 'userPrincipalName';Mail=Get-Prop $u 'mail';Department=Get-Prop $u 'department';JobTitle=Get-Prop $u 'jobTitle';CompanyName=Get-Prop $u 'companyName';AccountEnabled=Get-Prop $u 'accountEnabled';UserType=Get-Prop $u 'userType';EmployeeId=Get-Prop $u 'employeeId';CreatedDateTime=Get-Prop $u 'createdDateTime'};$users+=$row;if($row.Id){$usersById[$row.Id]=$row}}
$groups=@();foreach($g in @($rawGroups)){$cat=Get-GroupCategory $g;if($SecurityOnly -and $cat -ne 'Security'){continue};if($MailEnabledSecurityOnly -and $cat -ne 'MailEnabledSecurity'){continue};if($DistributionListOnly -and $cat -ne 'DistributionList'){continue};if($Microsoft365Only -and $cat -ne 'Microsoft365'){continue};$groups+=$g}
$filteredIds=@{};foreach($g in @($groups)){$filteredIds[(Get-Prop $g 'id')]=$true}
$memberRows=@();foreach($m in @($memberCacheRows)){if(-not $filteredIds.ContainsKey($m.GroupId)){continue};$prof=$null;if($usersById.ContainsKey($m.MemberId)){$prof=$usersById[$m.MemberId]};$dep='';$jt='';$co='';$en=$null;$ut='';$emp='';$upn=$m.MemberUPN;$mail=$m.MemberMail;if($prof){$dep=$prof.Department;$jt=$prof.JobTitle;$co=$prof.CompanyName;$en=$prof.AccountEnabled;$ut=$prof.UserType;$emp=$prof.EmployeeId;if(-not $upn){$upn=$prof.UserPrincipalName};if(-not $mail){$mail=$prof.Mail}};$memberRows+=[pscustomobject]@{GroupId=$m.GroupId;GroupName=$m.GroupName;GroupMail=$m.GroupMail;GroupCategory=$m.GroupCategory;GroupSecurityEnabled=$m.GroupSecurityEnabled;GroupMailEnabled=$m.GroupMailEnabled;GroupTypes=$m.GroupTypes;GroupIsAssignableToRole=$m.GroupIsAssignableToRole;GroupMembershipRule=$m.GroupMembershipRule;MembershipRuleState=$m.MembershipRuleState;MembershipMode=$m.MembershipMode;MemberId=$m.MemberId;MemberDisplayName=$m.MemberDisplayName;MemberUPN=$upn;MemberMail=$mail;MemberType=$m.MemberType;MemberDepartment=$dep;MemberJobTitle=$jt;MemberCompanyName=$co;MemberAccountEnabled=$en;MemberUserType=$ut;MemberEmployeeId=$emp}}
$enabledUsers=@($users|Where-Object{$_.AccountEnabled -eq $true}).Count;$totalRows=@($memberRows).Count;$ownerCounts=@{};foreach($og in (@($ownerRows)|Group-Object GroupId)){$ownerCounts[$og.Name]=$og.Count}
$groupRows=@();foreach($g in @($groups)){$gid=Get-Prop $g 'id';$gn=Get-Prop $g 'displayName';$rows=@($memberRows|Where-Object{$_.GroupId -eq $gid});$um=@($rows|Where-Object{$_.MemberType -eq 'User'});$depts=@($um|Where-Object{$_.MemberDepartment}|Select-Object -ExpandProperty MemberDepartment -Unique);$deptGroups=@($um|Where-Object{$_.MemberDepartment}|Group-Object MemberDepartment|Sort-Object @{Expression='Count';Descending=$true});$pd='';$pdc=0;if($deptGroups.Count -gt 0){$pd=$deptGroups[0].Name;$pdc=$deptGroups[0].Count};$mc=$rows.Count;$uuc=@($um|Select-Object -ExpandProperty MemberId -Unique).Count;$auc=@($um|Where-Object{$_.MemberAccountEnabled -eq $true}|Select-Object -ExpandProperty MemberId -Unique).Count;$den=Convert-Percent $mc $totalRows;$cov=Convert-Percent $auc $enabledUsers;$own=0;if($ownerCounts.ContainsKey($gid)){$own=$ownerCounts[$gid]};if($IsEmpty -and $mc -ne 0){continue};if($MinGroupMembersCount -gt 0 -and $mc -lt $MinGroupMembersCount){continue};$rule=Get-Prop $g 'membershipRule';$isDyn=-not[string]::IsNullOrWhiteSpace([string]$rule);$isCross=@($depts).Count -gt 1;$isHigh=$den -ge $HighDensityPctThreshold;$groupRows+=[pscustomobject]@{GroupId=$gid;GroupName=$gn;GroupMail=Get-Prop $g 'mail';GroupCategory=Get-GroupCategory $g;SecurityEnabled=Get-Prop $g 'securityEnabled';MailEnabled=Get-Prop $g 'mailEnabled';GroupTypes=Get-GroupTypesText $g;IsDynamicGroup=$isDyn;MembershipRule=$rule;MembershipRuleState=Get-Prop $g 'membershipRuleProcessingState';IsAssignableToRole=Get-Prop $g 'isAssignableToRole';OwnerCount=$own;MemberCount=$mc;UserMemberCount=$uuc;ActiveUserMemberCount=$auc;DepartmentCount=@($depts).Count;BlankDepartmentMemberCount=@($um|Where-Object{-not $_.MemberDepartment}).Count;PrimaryDepartment=$pd;PrimaryDepartmentCount=$pdc;PrimaryDepartmentPctOfGroup=Convert-Percent $pdc @($um).Count;MembershipDensityPct=$den;UserCoveragePct=$cov;IsCrossDepartmentGroup=$isCross;IsHighDensityGroup=$isHigh;CreatedDateTime=Get-Prop $g 'createdDateTime';Visibility=Get-Prop $g 'visibility'}}
$groupRows=@($groupRows|Sort-Object @{Expression='MembershipDensityPct';Descending=$true},@{Expression='GroupName';Ascending=$true});$allowed=@{};foreach($gr in $groupRows){$allowed[$gr.GroupId]=$true};$memberOut=@($memberRows|Where-Object{$allowed.ContainsKey($_.GroupId)})
$deptTotals=@{};foreach($dg in (@($users)|Group-Object Department)){$dn=$dg.Name;if(-not $dn){$dn='(blank)'};$deptTotals[$dn]=$dg.Count}
$deptRows=@();foreach($gd in (@($memberOut)|Where-Object{$_.MemberType -eq 'User'}|Group-Object GroupId,MemberDepartment)){$s=$gd.Group[0];$dn=$s.MemberDepartment;if(-not $dn){$dn='(blank)'};$uc=@($gd.Group|Select-Object -ExpandProperty MemberId -Unique).Count;$dt=0;if($deptTotals.ContainsKey($dn)){$dt=$deptTotals[$dn]};$gr=@($groupRows|Where-Object{$_.GroupId -eq $s.GroupId}|Select-Object -First 1);$gu=0;$gden=0;if($gr){$gu=$gr[0].UserMemberCount;$gden=$gr[0].MembershipDensityPct};$deptRows+=[pscustomobject]@{Department=$dn;GroupId=$s.GroupId;GroupName=$s.GroupName;GroupCategory=$s.GroupCategory;UsersInDepartmentInGroup=$uc;DepartmentTotalUsers=$dt;DepartmentCoveragePctForGroup=Convert-Percent $uc $dt;GroupShareFromDepartmentPct=Convert-Percent $uc $gu;GroupMembershipDensityPct=$gden;IsRoleAssignableGroup=$s.GroupIsAssignableToRole;IsDynamicGroup=(-not[string]::IsNullOrWhiteSpace([string]$s.GroupMembershipRule))}}
$deptRows=@($deptRows|Sort-Object @{Expression='GroupMembershipDensityPct';Descending=$true},@{Expression='GroupName';Ascending=$true})
$exceptions=@();foreach($gr in $groupRows){if(-not $SkipOwners -and $gr.OwnerCount -eq 0){$exceptions+=[pscustomobject]@{Severity='Medium';Finding='Group has no owner';GroupId=$gr.GroupId;GroupName=$gr.GroupName;Detail='OwnerCount=0'}};if($gr.IsHighDensityGroup){$exceptions+=[pscustomobject]@{Severity='Review';Finding='High group density';GroupId=$gr.GroupId;GroupName=$gr.GroupName;Detail="MembershipDensityPct=$($gr.MembershipDensityPct)"}};if($gr.IsCrossDepartmentGroup){$exceptions+=[pscustomobject]@{Severity='Review';Finding='Cross-department group';GroupId=$gr.GroupId;GroupName=$gr.GroupName;Detail="DepartmentCount=$($gr.DepartmentCount)"}};if($gr.IsAssignableToRole){$exceptions+=[pscustomobject]@{Severity='High';Finding='Role-assignable group';GroupId=$gr.GroupId;GroupName=$gr.GroupName;Detail='IsAssignableToRole=True'}}}
$run=Get-Date -Format 'yyyyMMdd-HHmmss';$out=Join-Path $OutputRoot $run;New-Item -ItemType Directory -Path $out -Force|Out-Null
Write-Stage 'Writing CSV evidence';Export-CsvSafe $users (Join-Path $out 'IdentityAudit-Users.csv');Export-CsvSafe $groupRows (Join-Path $out 'IdentityAudit-Groups.csv');Export-CsvSafe $memberOut (Join-Path $out 'IdentityAudit-GroupMembers.csv');Export-CsvSafe $ownerRows (Join-Path $out 'IdentityAudit-GroupOwners.csv');Export-CsvSafe $deptRows (Join-Path $out 'IdentityAudit-DepartmentGroupMatrix.csv');Export-CsvSafe ($groupRows|Select-Object GroupName,GroupId,GroupCategory,MemberCount,UserMemberCount,ActiveUserMemberCount,MembershipDensityPct,UserCoveragePct,DepartmentCount,PrimaryDepartment,PrimaryDepartmentPctOfGroup,OwnerCount,IsDynamicGroup,IsAssignableToRole,IsHighDensityGroup) (Join-Path $out 'IdentityAudit-GroupDensity.csv');Export-CsvSafe $exceptions (Join-Path $out 'IdentityAudit-Exceptions.csv')
Write-Stage 'Building graph analytics'
$nodes=@{};$edges=@();$groupById=@{};foreach($u in @($users)){Add-Node $nodes $u.Id ($(if($u.UserPrincipalName){$u.UserPrincipalName}else{$u.DisplayName})) 'User' $u.UserType};foreach($g in @($groupRows)){Add-Node $nodes $g.GroupId $g.GroupName 'Group' $g.GroupCategory;$groupById[$g.GroupId]=$g};foreach($m in @($memberOut)){Add-Node $nodes $m.MemberId ($(if($m.MemberUPN){$m.MemberUPN}else{$m.MemberDisplayName})) $m.MemberType ''; $edges+=New-Edge $m.MemberId $m.GroupId 'MemberOf' ($(if($m.MemberUPN){$m.MemberUPN}else{$m.MemberDisplayName})) $m.GroupName $m.MemberType 'Group'};foreach($o in @($ownerRows)){Add-Node $nodes $o.OwnerId ($(if($o.OwnerUPN){$o.OwnerUPN}else{$o.OwnerDisplayName})) $o.OwnerType ''; $edges+=New-Edge $o.OwnerId $o.GroupId 'OwnsGroup' ($(if($o.OwnerUPN){$o.OwnerUPN}else{$o.OwnerDisplayName})) $o.GroupName $o.OwnerType 'Group'}
$groupEdges=@($edges|Where-Object{$_.SourceType -eq 'Group' -and $_.EdgeType -eq 'MemberOf'});$adj=@{};foreach($e in $groupEdges){if(-not $adj.ContainsKey($e.SourceId)){$adj[$e.SourceId]=@()};$adj[$e.SourceId]+=$e.TargetId}
$highTargets=@{};foreach($g in @($groupRows)){if($g.IsAssignableToRole -eq $true -or $g.GroupName -match $HighValueGroupPattern){$highTargets[$g.GroupId]=$true}}
$paths=@();foreach($e in @($edges|Where-Object{$_.SourceType -eq 'User' -or $_.SourceType -eq 'Group' -or $_.SourceType -eq 'ServicePrincipal'})){if($highTargets.ContainsKey($e.TargetId)){continue};$p=Find-ShortestPath $adj $e.TargetId $highTargets $MaxPathDepth;if(@($p).Count -gt 0){$labels=@();foreach($id in @($p)){if($groupById.ContainsKey($id)){$labels+=$groupById[$id].GroupName}else{$labels+=$id}};$paths+=[pscustomobject]@{StartId=$e.SourceId;StartLabel=$e.SourceLabel;StartType=$e.SourceType;EntryGroup=$e.TargetLabel;TargetGroup=$labels[-1];HopCount=@($p).Count;Path=($e.SourceLabel+' -> '+($labels -join ' -> '));Risk='High'}}}
$cycles=Find-Cycles $adj $MaxPathDepth
$nestedStats=@();foreach($g in @($groupRows)){$gid=$g.GroupId;$contains=@($groupEdges|Where-Object{$_.TargetId -eq $gid}).Count;$nestedInto=@($groupEdges|Where-Object{$_.SourceId -eq $gid}).Count;$nestedStats+=[pscustomobject]@{GroupId=$gid;GroupName=$g.GroupName;NestedGroupMemberCount=$contains;NestedIntoGroupCount=$nestedInto;MemberCount=[int]$g.MemberCount;DepartmentCount=[int]$g.DepartmentCount}}
$riskRows=@();foreach($g in @($groupRows)){$score=0;$drivers=@();if($g.IsAssignableToRole -eq $true){$score+=50;$drivers+='Role-assignable'};if([int]$g.OwnerCount -eq 0){$score+=20;$drivers+='Ownerless'};if($g.IsHighDensityGroup -eq $true){$score+=20;$drivers+='High density'};if($g.IsCrossDepartmentGroup -eq $true){$score+=15;$drivers+='Cross-department'};if($g.IsDynamicGroup -eq $true){$score+=5;$drivers+='Dynamic'};if([int]$g.DepartmentCount -gt 5){$score+=10;$drivers+='Many departments'};if([int]$g.MemberCount -gt 500){$score+=10;$drivers+='Large membership'};$ns=@($nestedStats|Where-Object{$_.GroupId -eq $g.GroupId}|Select-Object -First 1);if($ns -and ($ns.NestedGroupMemberCount -gt 0 -or $ns.NestedIntoGroupCount -gt 0)){$score+=10;$drivers+='Nested group'};$pc=@($paths|Where-Object{$_.EntryGroup -eq $g.GroupName -or $_.TargetGroup -eq $g.GroupName}).Count;if($pc -gt 0){$score+=25;$drivers+='Privileged path'};$riskRows+=[pscustomobject]@{GroupId=$g.GroupId;GroupName=$g.GroupName;RiskScore=$score;RiskDrivers=($drivers -join '; ');MemberCount=$g.MemberCount;OwnerCount=$g.OwnerCount;DepartmentCount=$g.DepartmentCount;MembershipDensityPct=$g.MembershipDensityPct;UserCoveragePct=$g.UserCoveragePct;PrivilegedPathCount=$pc;IsAssignableToRole=$g.IsAssignableToRole;IsDynamicGroup=$g.IsDynamicGroup}}
$riskRows=@($riskRows|Sort-Object @{Expression='RiskScore';Descending=$true},@{Expression='GroupName';Ascending=$true});$nodesOut=@($nodes.Values);foreach($n in $nodesOut){if($n.Type -eq 'Group'){$r=@($riskRows|Where-Object{$_.GroupId -eq $n.Id}|Select-Object -First 1);if($r){$n.RiskScore=$r[0].RiskScore;$n.RiskDrivers=$r[0].RiskDrivers}}}
CsvSafe $nodesOut (Join-Path $out 'IdentityAudit-Nodes.csv');CsvSafe $edges (Join-Path $out 'IdentityAudit-Edges.csv');CsvSafe $paths (Join-Path $out 'IdentityAudit-PrivilegedPaths.csv');CsvSafe $cycles (Join-Path $out 'IdentityAudit-CircularNesting.csv');CsvSafe $nestedStats (Join-Path $out 'IdentityAudit-NestingStats.csv');CsvSafe $riskRows (Join-Path $out 'IdentityAudit-RiskScores.csv');[pscustomobject]@{nodes=$nodesOut;edges=$edges;paths=$paths;cycles=$cycles;riskScores=$riskRows}|ConvertTo-Json -Depth 6|Out-File (Join-Path $out 'IdentityAudit-Graph.json') -Encoding utf8
Write-Stage 'Writing dashboards'
$css="<style>body{font-family:Segoe UI,Arial;margin:32px;background:#f5f7fb;color:#172033}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px}.card,.panel{background:#fff;border:1px solid #d9e0ec;border-radius:12px;padding:14px;margin:14px 0}.value{font-size:28px;font-weight:700}.muted{color:#667}table{border-collapse:collapse;width:100%;font-size:13px}td,th{border-bottom:1px solid #edf1f7;padding:7px;text-align:left}</style>"
$std="<!doctype html><html><head><meta charset='utf-8'><title>Identity Audit Dashboard</title>$css</head><body><h1>Identity Audit Dashboard</h1><p class='muted'>Run $run | Tenant $(HtmlSafe $TenantId) | Cache root $(HtmlSafe $CacheRoot)</p><div class='cards'><div class='card'>Groups<div class='value'>$(@($groupRows).Count)</div></div><div class='card'>Users<div class='value'>$(@($users).Count)</div></div><div class='card'>Membership rows<div class='value'>$totalRows</div></div><div class='card'>Ownerless groups<div class='value'>$(@($groupRows|Where-Object{$_.OwnerCount -eq 0}).Count)</div></div></div>";$std+=New-HtmlTable 'Top group density by membership percentage' (@($groupRows|Select-Object -First 25)) @('GroupName','GroupCategory','MemberCount','UserMemberCount','MembershipDensityPct','UserCoveragePct','DepartmentCount','PrimaryDepartment','OwnerCount','IsDynamicGroup','IsAssignableToRole');$std+=New-HtmlTable 'Department / group hotspots' (@($deptRows|Select-Object -First 25)) @('Department','GroupName','UsersInDepartmentInGroup','DepartmentTotalUsers','DepartmentCoveragePctForGroup','GroupShareFromDepartmentPct','GroupMembershipDensityPct');$std+='</body></html>';$stdDash=Join-Path $out 'IdentityAudit-Dashboard.html';$std|Out-File $stdDash -Encoding utf8
$graph="<!doctype html><html><head><meta charset='utf-8'><title>Identity Graph Analysis</title>$css</head><body><h1>Identity Graph Analysis</h1><p class='muted'>BloodHound-like graph analysis from Entra group, member, and owner evidence.</p><div class='cards'><div class='card'>Nodes<div class='value'>$(@($nodesOut).Count)</div></div><div class='card'>Edges<div class='value'>$(@($edges).Count)</div></div><div class='card'>High-value targets<div class='value'>$($highTargets.Count)</div></div><div class='card'>Privileged paths<div class='value'>$(@($paths).Count)</div></div><div class='card'>Circular nesting<div class='value'>$(@($cycles).Count)</div></div><div class='card'>Nested group edges<div class='value'>$(@($groupEdges).Count)</div></div></div>";$graph+=New-HtmlTable 'Top risk-scored groups' (@($riskRows|Select-Object -First 25)) @('GroupName','RiskScore','RiskDrivers','MemberCount','OwnerCount','DepartmentCount','MembershipDensityPct','PrivilegedPathCount') 25;$graph+=New-HtmlTable 'Privileged path candidates' (@($paths|Select-Object -First 50)) @('StartLabel','StartType','EntryGroup','TargetGroup','HopCount','Path','Risk') 50;$graph+=New-HtmlTable 'Circular group nesting' $cycles @('Length','Cycle') 50;$graph+=New-HtmlTable 'Nested group chokepoints' (@($nestedStats|Sort-Object @{Expression='NestedGroupMemberCount';Descending=$true},@{Expression='NestedIntoGroupCount';Descending=$true}|Select-Object -First 25)) @('GroupName','NestedGroupMemberCount','NestedIntoGroupCount','MemberCount','DepartmentCount') 25;$graph+='<p class="muted">Path findings are review candidates, not automatic violations.</p></body></html>';$graphDash=Join-Path $out 'IdentityAudit-GraphDashboard.html';$graph|Out-File $graphDash -Encoding utf8
@('# Identity Audit Evidence Manifest','',"Run ID: $run","Tenant ID: $TenantId","Cache root: $CacheRoot","Cache max age hours: $CacheMaxAgeHours",'','Outputs: users, groups, members, owners, department matrix, density, exceptions, graph nodes, graph edges, paths, cycles, risk scores, dashboards')|Out-File (Join-Path $out 'IdentityAudit-Manifest.md') -Encoding utf8
Write-Stage 'Complete';Write-Host "Output folder: $out";Write-Host "Dashboard: $stdDash";Write-Host "Graph dashboard: $graphDash";if($OpenDashboard){Invoke-Item $graphDash}
