<#
IdentityAudit.Graph_V3.ps1
Self-contained Graph REST identity audit with CSV outputs and HTML dashboard.
#>
[CmdletBinding()]
param(
  [string]${TenantId},[string]${ClientId},[string]${CertificateThumbprint},
  [string]${OutputRoot}='.\IdentityAudit-Evidence',[string]${GroupIdsFile},
  [switch]${IncludeTransitiveMembership},[switch]${SecurityOnly},[switch]${MailEnabledSecurityOnly},[switch]${DistributionListOnly},[switch]${Microsoft365Only},[switch]${IsEmpty},
  [int]${MinGroupMembersCount}=0,[decimal]${HighDensityPctThreshold}=5.0,[switch]${SkipOwners},[switch]${InstallModules},[switch]${OpenDashboard}
)
$ErrorActionPreference='Stop'
function Stage([string]$m){Write-Host "[IdentityAudit] $m" -ForegroundColor Cyan}
function Warn([string]$m){Write-Host "[IdentityAudit][WARN] $m" -ForegroundColor Yellow}
function NeedModule([string]$n){if(-not(Get-Module -ListAvailable -Name $n)){if($InstallModules){Install-Module $n -Scope CurrentUser -Force -AllowClobber}else{throw "Missing module $n. Use -InstallModules."}};Import-Module $n -ErrorAction Stop}
function P($o,[string]$n){if($null -eq $o){return $null};$p=$o.PSObject.Properties[$n];if($null -ne $p){return $p.Value};try{return $o[$n]}catch{return $null}}
function GGet([string]$u){try{$r=Invoke-MgGraphRequest -Method GET -Uri $u -OutputType HttpResponseMessage;$c=$r.Content.ReadAsStringAsync().GetAwaiter().GetResult();if([string]::IsNullOrWhiteSpace($c)){return $null};return Microsoft.PowerShell.Utility\ConvertFrom-Json -InputObject $c}catch{throw "Graph GET failed. Uri='$u'. Error='$($_.Exception.Message)'"}}
function GPaged([string]$u){$rows=New-Object System.Collections.Generic.List[object];$next=$u;while(-not[string]::IsNullOrWhiteSpace([string]$next)){$pg=GGet $next;$vals=P $pg 'value';foreach($i in @($vals)){if($null -ne $i){[void]$rows.Add($i)}};$next=P $pg '@odata.nextLink'};return $rows.ToArray()}
function ObjType($o){$t=[string](P $o '@odata.type');if($t -match 'user$'){return 'User'};if($t -match 'group$'){return 'Group'};if($t -match 'servicePrincipal$'){return 'ServicePrincipal'};if($t -match 'device$'){return 'Device'};return 'DirectoryObject'}
function DName($o){$v=P $o 'displayName';if([string]::IsNullOrWhiteSpace([string]$v)){$v=P $o 'userPrincipalName'};if([string]::IsNullOrWhiteSpace([string]$v)){$v=P $o 'mail'};return $v}
function GTypes($g){$gt=P $g 'groupTypes';if($null -eq $gt){return ''};return @($gt)-join ';'}
function GCat($g){$gt=GTypes $g;$s=P $g 'securityEnabled';$m=P $g 'mailEnabled';if($gt -match 'Unified'){return 'Microsoft365'};if($s -eq $true -and $m -eq $true){return 'MailEnabledSecurity'};if($s -eq $true){return 'Security'};if($m -eq $true){return 'DistributionList'};return 'Other'}
function Pct([decimal]$n,[decimal]$d){if($d -le 0){return [decimal]0};return [math]::Round(($n/$d)*100,2)}
function H($v){if($null -eq $v){return ''};return [System.Net.WebUtility]::HtmlEncode([string]$v)}
function T([string]$title,$rows,[string[]]$cols){$h="<section class='panel'><h2>$(H $title)</h2>";if(-not $rows -or @($rows).Count -eq 0){return $h+'<p>No records found.</p></section>'};$h+='<table><thead><tr>';foreach($c in $cols){$h+="<th>$(H $c)</th>"};$h+='</tr></thead><tbody>';foreach($r in @($rows|Select-Object -First 25)){$h+='<tr>';foreach($c in $cols){$v='';if($r.PSObject.Properties.Name -contains $c){$v=$r.$c};$h+="<td>$(H $v)</td>"};$h+='</tr>'};return $h+'</tbody></table></section>'}

Stage 'Preparing modules';NeedModule 'Microsoft.Graph.Authentication'
$run=Get-Date -Format 'yyyyMMdd-HHmmss';$out=Join-Path $OutputRoot $run;New-Item -ItemType Directory -Path $out -Force|Out-Null
$mode='Direct';if($IncludeTransitiveMembership){$mode='Transitive'}
try{
 Stage 'Connecting to Microsoft Graph'
 if($TenantId -and $ClientId -and $CertificateThumbprint){Connect-MgGraph -TenantId $TenantId -ClientId $ClientId -CertificateThumbprint $CertificateThumbprint -NoWelcome}else{Connect-MgGraph -Scopes @('User.Read.All','Group.Read.All','GroupMember.Read.All','Directory.Read.All') -NoWelcome}
 if(-not $TenantId){$TenantId=(Get-MgContext).TenantId}
 Stage 'Collecting users'
 $rawUsers=@(GPaged '/v1.0/users?$select=id,displayName,userPrincipalName,mail,department,jobTitle,companyName,accountEnabled,userType,employeeId,createdDateTime&$top=999')
 $users=@();$usersById=@{}
 foreach($u in $rawUsers){$row=[pscustomobject]@{Id=P $u 'id';DisplayName=P $u 'displayName';UserPrincipalName=P $u 'userPrincipalName';Mail=P $u 'mail';Department=P $u 'department';JobTitle=P $u 'jobTitle';CompanyName=P $u 'companyName';AccountEnabled=P $u 'accountEnabled';UserType=P $u 'userType';EmployeeId=P $u 'employeeId';CreatedDateTime=P $u 'createdDateTime'};$users+=$row;if($row.Id){$usersById[$row.Id]=$row}}
 Stage 'Collecting groups'
 if($GroupIdsFile){$rawGroups=@();foreach($gid in (Get-Content $GroupIdsFile|Where-Object{$_})){$id=$gid.Trim();try{$rawGroups+=GGet "/v1.0/groups/$id?`$select=id,displayName,description,mail,mailEnabled,securityEnabled,groupTypes,membershipRule,membershipRuleProcessingState,isAssignableToRole,createdDateTime,visibility"}catch{$rawGroups+=GGet "/v1.0/groups/$id?`$select=id,displayName,description,mail,mailEnabled,securityEnabled,groupTypes,createdDateTime"}}}else{try{$rawGroups=@(GPaged '/v1.0/groups?$select=id,displayName,description,mail,mailEnabled,securityEnabled,groupTypes,membershipRule,membershipRuleProcessingState,isAssignableToRole,createdDateTime,visibility&$top=999')}catch{Warn "Advanced group properties failed; using baseline. $($_.Exception.Message)";$rawGroups=@(GPaged '/v1.0/groups?$select=id,displayName,description,mail,mailEnabled,securityEnabled,groupTypes,createdDateTime&$top=999')}}
 $groups=@();foreach($g in $rawGroups){$cat=GCat $g;if($SecurityOnly -and $cat -ne 'Security'){continue};if($MailEnabledSecurityOnly -and $cat -ne 'MailEnabledSecurity'){continue};if($DistributionListOnly -and $cat -ne 'DistributionList'){continue};if($Microsoft365Only -and $cat -ne 'Microsoft365'){continue};$groups+=$g}
 $members=@();$owners=@();$i=0
 foreach($g in $groups){$i++;$gid=P $g 'id';$gn=P $g 'displayName';Write-Progress -Activity 'Collecting group membership' -Status $gn -PercentComplete (($i/[math]::Max(1,$groups.Count))*100);$cat=GCat $g;$gt=GTypes $g;$gm=P $g 'mail';$se=P $g 'securityEnabled';$me=P $g 'mailEnabled';$ra=P $g 'isAssignableToRole';$rule=P $g 'membershipRule';$rs=P $g 'membershipRuleProcessingState';$ep='members';if($IncludeTransitiveMembership){$ep='transitiveMembers'};try{$ms=@(GPaged "/v1.0/groups/$gid/$ep?`$select=id,displayName,userPrincipalName,mail&`$top=999")}catch{Warn "Members failed for $gn. $($_.Exception.Message)";$ms=@()};foreach($m in $ms){$mid=P $m 'id';$mt=ObjType $m;$prof=$null;if($usersById.ContainsKey($mid)){$prof=$usersById[$mid]};$dep='';$jt='';$co='';$en=$null;$ut='';$emp='';$upn=P $m 'userPrincipalName';$mail=P $m 'mail';if($prof){$dep=$prof.Department;$jt=$prof.JobTitle;$co=$prof.CompanyName;$en=$prof.AccountEnabled;$ut=$prof.UserType;$emp=$prof.EmployeeId;if(-not $upn){$upn=$prof.UserPrincipalName};if(-not $mail){$mail=$prof.Mail}};$members+=[pscustomobject]@{GroupId=$gid;GroupName=$gn;GroupMail=$gm;GroupCategory=$cat;GroupSecurityEnabled=$se;GroupMailEnabled=$me;GroupTypes=$gt;GroupIsAssignableToRole=$ra;GroupMembershipRule=$rule;MembershipRuleState=$rs;MembershipMode=$mode;MemberId=$mid;MemberDisplayName=DName $m;MemberUPN=$upn;MemberMail=$mail;MemberType=$mt;MemberDepartment=$dep;MemberJobTitle=$jt;MemberCompanyName=$co;MemberAccountEnabled=$en;MemberUserType=$ut;MemberEmployeeId=$emp}}
 if(-not $SkipOwners){try{$os=@(GPaged "/v1.0/groups/$gid/owners?`$select=id,displayName,userPrincipalName,mail&`$top=999")}catch{$os=@()};foreach($o in $os){$owners+=[pscustomobject]@{GroupId=$gid;GroupName=$gn;GroupCategory=$cat;OwnerId=P $o 'id';OwnerDisplayName=DName $o;OwnerUPN=P $o 'userPrincipalName';OwnerType=ObjType $o}}}
 }
 Write-Progress -Activity 'Collecting group membership' -Completed
 $enabledUsers=@($users|Where-Object{$_.AccountEnabled -eq $true}).Count;$totalRows=@($members).Count;$ownerCounts=@{};foreach($og in (@($owners)|Group-Object GroupId)){$ownerCounts[$og.Name]=$og.Count}
 $groupRows=@();foreach($g in $groups){$gid=P $g 'id';$gn=P $g 'displayName';$rows=@($members|Where-Object{$_.GroupId -eq $gid});$um=@($rows|Where-Object{$_.MemberType -eq 'User'});$depts=@($um|Where-Object{$_.MemberDepartment}|Select-Object -ExpandProperty MemberDepartment -Unique);$deptGroups=@($um|Where-Object{$_.MemberDepartment}|Group-Object MemberDepartment|Sort-Object Count -Descending);$pd='';$pdc=0;if($deptGroups.Count -gt 0){$pd=$deptGroups[0].Name;$pdc=$deptGroups[0].Count};$mc=$rows.Count;$uuc=@($um|Select-Object -ExpandProperty MemberId -Unique).Count;$auc=@($um|Where-Object{$_.MemberAccountEnabled -eq $true}|Select-Object -ExpandProperty MemberId -Unique).Count;$den=Pct $mc $totalRows;$cov=Pct $auc $enabledUsers;$own=0;if($ownerCounts.ContainsKey($gid)){$own=$ownerCounts[$gid]};if($IsEmpty -and $mc -ne 0){continue};if($MinGroupMembersCount -gt 0 -and $mc -lt $MinGroupMembersCount){continue};$rule=P $g 'membershipRule';$groupRows+=[pscustomobject]@{GroupId=$gid;GroupName=$gn;GroupMail=P $g 'mail';GroupCategory=GCat $g;SecurityEnabled=P $g 'securityEnabled';MailEnabled=P $g 'mailEnabled';GroupTypes=GTypes $g;IsDynamicGroup=(-not [string]::IsNullOrWhiteSpace([string]$rule));MembershipRule=$rule;MembershipRuleState=P $g 'membershipRuleProcessingState';IsAssignableToRole=P $g 'isAssignableToRole';OwnerCount=$own;MemberCount=$mc;UserMemberCount=$uuc;ActiveUserMemberCount=$auc;DepartmentCount=@($depts).Count;BlankDepartmentMemberCount=@($um|Where-Object{-not $_.MemberDepartment}).Count;PrimaryDepartment=$pd;PrimaryDepartmentCount=$pdc;PrimaryDepartmentPctOfGroup=Pct $pdc @($um).Count;MembershipDensityPct=$den;UserCoveragePct=$cov;IsCrossDepartmentGroup=(@($depts).Count -gt 1);IsHighDensityGroup=($den -ge $HighDensityPctThreshold);CreatedDateTime=P $g 'createdDateTime';Visibility=P $g 'visibility'}}
 $groupRows=@($groupRows|Sort-Object @{Expression='MembershipDensityPct';Descending=$true},@{Expression='GroupName';Ascending=$true})
 $allowed=@{};foreach($gr in $groupRows){$allowed[$gr.GroupId]=$true};$memberOut=@($members|Where-Object{$allowed.ContainsKey($_.GroupId)})
 $deptTotals=@{};foreach($dg in (@($users)|Group-Object Department)){$dn=$dg.Name;if(-not $dn){$dn='(blank)'};$deptTotals[$dn]=$dg.Count}
 $deptRows=@();foreach($gd in (@($memberOut)|Where-Object{$_.MemberType -eq 'User'}|Group-Object GroupId,MemberDepartment)){$s=$gd.Group[0];$dn=$s.MemberDepartment;if(-not $dn){$dn='(blank)'};$uCount=@($gd.Group|Select-Object -ExpandProperty MemberId -Unique).Count;$dt=0;if($deptTotals.ContainsKey($dn)){$dt=$deptTotals[$dn]};$gr=@($groupRows|Where-Object{$_.GroupId -eq $s.GroupId}|Select-Object -First 1);$gu=0;$gden=0;if($gr){$gu=$gr[0].UserMemberCount;$gden=$gr[0].MembershipDensityPct};$deptRows+=[pscustomobject]@{Department=$dn;GroupId=$s.GroupId;GroupName=$s.GroupName;GroupCategory=$s.GroupCategory;UsersInDepartmentInGroup=$uCount;DepartmentTotalUsers=$dt;DepartmentCoveragePctForGroup=Pct $uCount $dt;GroupShareFromDepartmentPct=Pct $uCount $gu;GroupMembershipDensityPct=$gden;IsRoleAssignableGroup=$s.GroupIsAssignableToRole;IsDynamicGroup=(-not[string]::IsNullOrWhiteSpace([string]$s.GroupMembershipRule))}}
 $deptRows=@($deptRows|Sort-Object @{Expression='GroupMembershipDensityPct';Descending=$true},@{Expression='GroupName';Ascending=$true})
 $exceptions=@();foreach($gr in $groupRows){if(-not $SkipOwners -and $gr.OwnerCount -eq 0){$exceptions+=[pscustomobject]@{Severity='Medium';Finding='Group has no owner';GroupId=$gr.GroupId;GroupName=$gr.GroupName;Detail='OwnerCount=0'}};if($gr.IsHighDensityGroup){$exceptions+=[pscustomobject]@{Severity='Review';Finding='High group density';GroupId=$gr.GroupId;GroupName=$gr.GroupName;Detail="MembershipDensityPct=$($gr.MembershipDensityPct)"}};if($gr.IsCrossDepartmentGroup){$exceptions+=[pscustomobject]@{Severity='Review';Finding='Cross-department group';GroupId=$gr.GroupId;GroupName=$gr.GroupName;Detail="DepartmentCount=$($gr.DepartmentCount)"}};if($gr.IsAssignableToRole){$exceptions+=[pscustomobject]@{Severity='High';Finding='Role-assignable group';GroupId=$gr.GroupId;GroupName=$gr.GroupName;Detail='IsAssignableToRole=True'}}}
 Stage 'Writing CSV evidence'
 $users|Export-Csv (Join-Path $out 'IdentityAudit-Users.csv') -NoTypeInformation;$groupRows|Export-Csv (Join-Path $out 'IdentityAudit-Groups.csv') -NoTypeInformation;$memberOut|Export-Csv (Join-Path $out 'IdentityAudit-GroupMembers.csv') -NoTypeInformation;$owners|Export-Csv (Join-Path $out 'IdentityAudit-GroupOwners.csv') -NoTypeInformation;$deptRows|Export-Csv (Join-Path $out 'IdentityAudit-DepartmentGroupMatrix.csv') -NoTypeInformation;$groupRows|Select-Object GroupName,GroupId,GroupCategory,MemberCount,UserMemberCount,ActiveUserMemberCount,MembershipDensityPct,UserCoveragePct,DepartmentCount,PrimaryDepartment,PrimaryDepartmentPctOfGroup,OwnerCount,IsDynamicGroup,IsAssignableToRole,IsHighDensityGroup|Export-Csv (Join-Path $out 'IdentityAudit-GroupDensity.csv') -NoTypeInformation;$exceptions|Export-Csv (Join-Path $out 'IdentityAudit-Exceptions.csv') -NoTypeInformation
 Stage 'Writing dashboard'
 $css="<style>body{font-family:Segoe UI,Arial;margin:32px;background:#f5f7fb;color:#172033}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.card,.panel{background:#fff;border:1px solid #d9e0ec;border-radius:12px;padding:14px;margin:14px 0}.value{font-size:26px;font-weight:700}table{border-collapse:collapse;width:100%;font-size:13px}td,th{border-bottom:1px solid #edf1f7;padding:7px;text-align:left}</style>"
 $topD=@($groupRows|Select-Object -First 25);$topC=@($groupRows|Sort-Object UserCoveragePct -Descending|Select-Object -First 25);$cross=@($groupRows|Where-Object{$_.IsCrossDepartmentGroup}|Select-Object -First 25);$ownerless=@($groupRows|Where-Object{$_.OwnerCount -eq 0}|Select-Object -First 25);$dyn=@($groupRows|Where-Object{$_.IsDynamicGroup}|Select-Object -First 25);$hot=@($deptRows|Select-Object -First 25)
 $html="<!doctype html><html><head><meta charset='utf-8'><title>Identity Audit Dashboard</title>$css</head><body><h1>Identity Audit Dashboard</h1><p>Run $run | Tenant $(H $TenantId) | Membership $mode</p><div class='cards'><div class='card'>Groups<div class='value'>$(@($groupRows).Count)</div></div><div class='card'>Users<div class='value'>$(@($users).Count)</div></div><div class='card'>Membership rows<div class='value'>$totalRows</div></div><div class='card'>Ownerless groups<div class='value'>$(@($ownerless).Count)</div></div></div>"
 $html+=T 'Top group density by membership percentage' $topD @('GroupName','GroupCategory','MemberCount','UserMemberCount','MembershipDensityPct','UserCoveragePct','DepartmentCount','PrimaryDepartment','OwnerCount','IsDynamicGroup','IsAssignableToRole')
 $html+=T 'Top groups by enabled user coverage percentage' $topC @('GroupName','GroupCategory','ActiveUserMemberCount','UserCoveragePct','MembershipDensityPct','DepartmentCount','PrimaryDepartment','OwnerCount')
 $html+=T 'Department / group hotspots' $hot @('Department','GroupName','UsersInDepartmentInGroup','DepartmentTotalUsers','DepartmentCoveragePctForGroup','GroupShareFromDepartmentPct','GroupMembershipDensityPct')
 $html+=T 'Cross-department groups' $cross @('GroupName','MemberCount','DepartmentCount','PrimaryDepartment','MembershipDensityPct','OwnerCount')
 $html+=T 'Ownerless groups' $ownerless @('GroupName','GroupCategory','MemberCount','MembershipDensityPct','DepartmentCount','IsDynamicGroup','IsAssignableToRole')
 $html+=T 'Dynamic groups' $dyn @('GroupName','GroupCategory','MemberCount','MembershipDensityPct','UserCoveragePct','DepartmentCount','PrimaryDepartment','MembershipRule')
 $html+='<p>Group density percentage = group membership rows divided by all membership rows observed in this run.</p></body></html>';$dash=Join-Path $out 'IdentityAudit-Dashboard.html';$html|Out-File $dash -Encoding utf8
 @('# Identity Audit Evidence Manifest','',"Run ID: $run","Tenant ID: $TenantId","Membership mode: $mode",'','Outputs: users, groups, members, owners, department matrix, density, exceptions, dashboard')|Out-File (Join-Path $out 'IdentityAudit-Manifest.md') -Encoding utf8
 Stage 'Complete';Write-Host "Output folder: $out";Write-Host "Dashboard: $dash";if($OpenDashboard){Invoke-Item $dash}
}finally{try{Disconnect-MgGraph|Out-Null}catch{}}
